/**
 * 폼 화면용 한글 번역 사전 (영문 원문 → 한글).
 * 화면 표시에만 쓰이고, 생성되는 Word 파일은 원본 영문 양식 그대로 유지된다.
 * 사전에 없는 문자열은 영문 원문이 그대로 노출된다.
 */
export const KO: Record<string, string> = {
  // ── 화면 공통
  'Inspection Report Builder': '검사 보고서 생성',
  'Fill in the form, attach photos, and download the Word report.':
    '양식을 선택해 입력하고, 사진을 첨부하면 Word 보고서로 내려받습니다.',
  'Upload': '직접 업로드',
  'Base Word file': '기본 Word 파일',
  'Photos': '사진 첨부',
  'Item': '물품',
  'Goods name': '물품 이름',
  'delete': '삭제',
  'Videos are delivered in a zip with the Word file, not inside it.':
    '동영상은 Word 안에 넣지 않고, 완성된 Word 파일과 함께 zip 으로 묶어 받습니다.',
  '+ add {x}': '+ {x} 추가',
  'jpg / jpeg / png / webp, multiple allowed': 'jpg / jpeg / png / webp, 여러 장 가능',
  'Done – download Word file': '완료 – Word 파일 다운로드',
  'Generating…': '생성 중...',
  'Selected': '선택됨',
  ' file(s) selected': '개 파일 선택됨',
  '+ add row': '+ 행 추가',
  'Uploaded files are not stored on the server; they are discarded right after the request.':
    '업로드 파일은 서버에 저장되지 않으며 요청 처리 후 즉시 폐기됩니다.',

  // ── 보고서 제목
  'CEC Inspection Report': 'CEC 검사 보고서',
  'PSIC Inspection Report (Scrap)': 'PSIC 검사 보고서 (스크랩)',
  'Pre-Shipment Inspection Report': '선적 전 검사 보고서',

  // ── 섹션 제목
  'General Information': '기본 정보',
  'GOODS DESCRIPTION / DECLARED / APPLIED FOR INSPECTION': '신고 물품 내역 / 검사 신청 내용',
  'INSPECTED': '검사 내역',
  'OPERATION TEST RESULT': '작동 시험 결과',
  'PACKING': '포장',
  'INSPECTION RESULT OF PACKING': '포장 검사 결과',
  'PHOTOGRAPHS OF INSPECTION ACTIVITY': '검사 활동 사진',
  'DOCUMENTS EXAMINED DURING INSPECTION': '검사 시 확인 문서',
  'DETAIL OF PRODUCT': '제품 상세',
  'ATTACHMENT': '첨부',
  'CONCLUSION OF INSPECTION': '검사 결론',
  'Applicant’s person(s) in charge': '신청인 측 입회자',
  'INSPECTOR': '검사원',
  'DECLARED / APPLIED FOR INSPECTION': '신고 내용 / 검사 신청 내용',
  'QUALITY': '품질',
  'RADIATION METER USED FOR INSPECTION': '검사에 사용한 방사선 측정기',
  'RADIATION LEVEL FOUND': '측정된 방사선 수치',
  'EXPLOSIVE MATERIAL': '폭발물',
  'ATTACHMENTS': '첨부 자료',
  'II. Inspection Result': 'II. 검사 결과',

  // ── 공통 필드
  'Result': '결과',
  'Date': '날짜',
  'Client': '고객사',
  'Job File No': 'Job File No (관리번호)',
  'Job File No.': 'Job File No (관리번호)',
  'Company name': '회사명',
  'Name': '성명',
  'Title': '직위',
  'Contact points (Tel., email, etc.)': '연락처 (전화, 이메일 등)',
  'Company name or CERINS branch office name': '회사명 또는 CERINS 지사명',
  'Yes': '예',
  'No': '아니오',
  'YES': '예',
  'NO': '아니오',
  'Others': '기타',
  'Other': '기타',
  'Quantity': '수량',
  'Manufacturer': '제조사',
  'Model': '모델',
  'Serial No.': '시리얼 번호',
  'Satisfactory': '적합',
  'Unsatisfactory': '부적합',
  'Conditional': '조건부',
  'Reject': '불합격',
  'Abortive': '검사 불능',
  'Re-inspection': '재검사',
  'Compliance': '적합',
  'If unsatisfactory result or conditional, specify the reasons': '부적합·조건부인 경우 사유',
  'If unsatisfactory result, specify the reasons': '부적합인 경우 사유',
  'If not satisfactory, specify the reasons': '적합이 아닌 경우 사유',

  // ── CEC
  'Declared goods description': '신고 물품 내역',
  'Product name (Representative)': '대표 품명',
  'Total Quantity': '총 수량',
  'Date of Inspection': '검사일',
  'Operation Test': '작동 시험',
  'Packing': '포장',
  'Loading Supervision': '적재 입회',
  'Place of Inspection and Country (full address)': '검사 장소 및 국가 (전체 주소)',
  'Round-Trip Travel Time (00:00 h)': '왕복 이동 시간 (00:00 h)',
  'Total Duration of Inspection Hours (00:00 h)': '총 검사 소요 시간 (00:00 h)',
  'Time of Operation Test / Packing Inspection / Loading Supervision':
    '작동 시험 / 포장 검사 / 적재 입회 시각',
  'OT Date': '작동시험 일자',
  'OT From': '작동시험 시작',
  'OT To': '작동시험 종료',
  'Pack Date': '포장 일자',
  'Pack From': '포장 시작',
  'Pack To': '포장 종료',
  'Load Date': '적재 일자',
  'Load From': '적재 시작',
  'Load To': '적재 종료',
  'TYPE OF PACKING': '포장 형태',
  'Bulk': '벌크',
  'Break-bulk': '브레이크벌크',
  'Container': '컨테이너',
  'In case of break-bulk and/or container cargo': '브레이크벌크 및/또는 컨테이너 화물인 경우',
  'Sl. No.': '번호',
  'Type of container (20’, 40’ …)': '컨테이너 종류 (20’, 40’ 등)',
  'LCL / FCL': 'LCL / FCL',
  'Container No.': '컨테이너 번호',
  'Seal No.': '봉인 번호',
  'Quantity & type of break-bulk packing': '브레이크벌크 포장 수량 및 종류',
  'Break-bulk: Type of packing': '브레이크벌크: 포장 종류',
  'Break-bulk: Quantity of packing': '브레이크벌크: 포장 수량',
  'Break-bulk: Remark if any': '브레이크벌크: 비고',
  'Other packing: Remark if any': '기타 포장: 비고',
  'Photograph(s) of the place of inspection with inspector': '검사 장소 + 검사원 사진 (필수)',
  'Photograph(s) of operation test at the place of inspection': '검사 장소에서의 작동 시험 사진',
  'Photographs of each goods/package showing their name-plates (at least 4)':
    '명판이 보이는 제품/포장별 사진 (4장 이상)',
  'Photographs of packing process': '포장 과정 사진',
  'Photographs of container stuffing and sealing process (at least 6)':
    '컨테이너 적입 및 봉인 과정 사진 (6장 이상)',
  'Documents examined': '확인 문서',
  'Inspection Checklist/Points provided by Coordinator': '코디네이터 제공 검사 체크리스트',
  'Original (Purchase) Price Copy': '원 구매가 사본',
  'Packing List': '패킹 리스트',
  'Proforma Invoice': '프로포마 인보이스',
  'Others – specify and attach/enclose': '기타 – 내용 기재 및 첨부',
  'Product details': '제품 상세',
  'Goods description': '품명',
  'Re-conditioned/repaired (Y/N)': '재생·수리 여부 (Y/N)',
  'Month & Year of manufacture': '제조 연월',
  'Model No./Serial No.': '모델/시리얼 번호',
  'Country of Origin': '원산지',
  'Nameplate (Y/N)': '명판 유무 (Y/N)',
  'Attachment (if any)': '첨부 여부',
  'If YES, list down and attach/enclose': '예인 경우 목록 작성 후 첨부',
  'Attachment': '첨부물',

  // ── SCRAP
  'Importer name': '수입자명',
  'Exporter name': '수출자명',
  'Product name': '품명',
  'Net weight': '순중량',
  'Grade type': '규격 종류',
  'ISRI grade': 'ISRI 등급',
  'Steel grade': '강종',
  'Date of inspection': '검사일',
  'Time of Inspection – From': '검사 시각 – 시작',
  'Time of Inspection – To': '검사 시각 – 종료',
  'Round-trip Travel Time': '왕복 이동 시간',
  'Total Duration of Inspection Hours': '총 검사 소요 시간',
  'Place of inspection (full address)': '검사 장소 (전체 주소)',
  'Quantity inspected / presented for inspection': '검사 수량 / 검사 제시 수량',
  'Country of origin': '원산지',
  'Weight – Net weight': '중량 – 순중량',
  'Weight – Gross weight': '중량 – 총중량',
  'Quality condition/grade': '품질 상태/등급',
  'Scrap': '스크랩',
  'Secondary': '2차 제품',
  'Defective': '불량품',
  'If other conditions or others are applicable, please specify': '기타에 해당하는 경우 내용',
  'Shredded or Un-shredded': '파쇄 여부',
  'Shredded': '파쇄',
  'Un-shredded': '미파쇄',
  'Mixed': '혼합',
  'If mixed, please specify': '혼합인 경우 내용',
  'Last date of calibration': '최근 교정일',
  'Next date of calibration': '차기 교정일',
  'Background radiation level (µSv/h)': '검사 장소 배경 방사선량 (µSv/h)',
  'Maximum radiation level on the scrap (µSv/h)': '스크랩 최대 방사선량 (µSv/h)',
  'Size of container (20’/40’…)': '컨테이너 규격 (20’/40’ 등)',
  'Quantity & type (KG)': '수량 및 종류 (KG)',
  'Container Radiation Level (µSv/h)': '컨테이너 방사선량 (µSv/h)',
  'Pictures taken during inspection (date & time shown)': '검사 중 촬영 사진 (날짜·시간 표시)',
  'Photograph(s) or video clipping of the place of inspection with PSIA inspector':
    '검사 장소 + PSIA 검사원 사진/영상',
  'Photograph(s) or video clipping of the testing instrument(s)': '검사 장비 사진/영상',
  'Photograph(s) or video clipping of the process of stuffing of containers': '컨테이너 적입 과정 사진/영상',
  'Photograph(s) or video clipping of the sealing process': '봉인 과정 사진/영상',
  'Video clips (at least 5 minutes)': '동영상 (5분 이상)',
  'Weight tickets': '계량 전표',
  'Documents examined during inspection': '검사 시 확인 문서',
  'Inspection checklist/point provided by Coordinator': '코디네이터 제공 검사 체크리스트',
  'Packing list': '패킹 리스트',
  'Proforma invoice': '프로포마 인보이스',
  'Weight ticket': '계량 전표',
  'Supplementary documents for quality/quantity': '품질·수량 입증 보조 문서',
  'Other documents if any': '기타 문서',
  'Others if any – specify and attach': '기타 – 내용 기재 및 첨부',

  // ── PSIC
  'ITEM NO': '품목 번호',
  'REPORT NO.': '보고서 번호',
  'Description': '품명',
  'BRAND': '브랜드',
  'Subcontractor': '협력업체',
  'Factory No': '공장 번호',
  'INSPECTION DATE': '검사일',
  'PI# & PO No.': 'PI / PO 번호',
  'Lot Size': '로트 수량',
  'BAR CODE NO.': '바코드 번호',
  'INSPECTION RESULT': '검사 결과',
  'PASSED': '합격',
  'FAILED': '불합격',
  'PENDING': '보류',
  'Remarks': '비고',
  'Inspector': '검사원',
  'Subcontractor By': '협력업체 담당',
  'Reviewed': '검토자',
};
