/**
 * 폼 화면용 베트남어 번역 사전 (영문 원문 → 베트남어).
 * 화면 표시에만 쓰이고, 생성되는 Word 파일은 원본 영문 양식 그대로 유지된다.
 * 사전에 없는 문자열은 영문 원문이 그대로 노출된다.
 */
export const VI: Record<string, string> = {
  // ── 화면 공통
  'Inspection Report Builder': 'Trình tạo báo cáo giám định',
  'Fill in the form, attach photos, and download the Word report.':
    'Điền vào biểu mẫu, đính kèm ảnh và tải báo cáo Word về.',
  'Upload': 'Tải lên trực tiếp',
  'Base Word file': 'Tệp Word gốc',
  'Photos': 'Ảnh đính kèm',
  'Item': 'Hàng hóa',
  'Goods name': 'Tên hàng hóa',
  'delete': 'Xóa',
  'Clear signature': 'Xóa chữ ký',
  'Reset form': 'Đặt lại biểu mẫu',
  'Entries are kept on this device, so you can close the browser and come back. Photos are not kept.':
    'Nội dung nhập được lưu trên thiết bị này, có thể đóng trình duyệt rồi quay lại. Ảnh không được lưu.',
  'Sign here with your mouse or finger.': 'Ký bằng chuột hoặc ngón tay.',
  'Videos are delivered in a zip with the Word file, not inside it.':
    'Video không được chèn vào tệp Word mà được gửi kèm trong tệp zip cùng tệp Word.',
  '+ add {x}': '+ Thêm {x}',
  'jpg / jpeg / png / webp, multiple allowed': 'jpg / jpeg / png / webp, có thể chọn nhiều tệp',
  'Done – download Word file': 'Hoàn tất – Tải tệp Word',
  'Generating…': 'Đang tạo…',
  'Selected': 'Đã chọn',
  ' file(s) selected': ' tệp đã chọn',
  '+ add row': '+ Thêm dòng',
  'Report name': 'Tên người lập báo cáo',
  'e.g. 유지환': 'Ví dụ) 유지환',
  'Saved as: 260828_Inspection Report_name':
    'Tên tệp lưu theo dạng: 260828_CEC Inspection Report_tên',
  'Admin page': 'Trang quản trị',
  'The generated report is stored on the server; admins can download it again from the admin page.':
    'Báo cáo được tạo sẽ lưu trên máy chủ; quản trị viên có thể tải lại từ trang quản trị.',

  // ── 보고서 제목
  'CEC Inspection Report': 'Báo cáo giám định CEC',
  'PSIC Inspection Report (Scrap)': 'Báo cáo giám định PSIC (phế liệu)',
  'Pre-Shipment Inspection Report': 'Báo cáo giám định trước khi giao hàng',

  // ── 섹션 제목
  'General Information': 'Thông tin chung',
  'GOODS DESCRIPTION / DECLARED / APPLIED FOR INSPECTION':
    'Mô tả hàng hóa khai báo / Nội dung đề nghị giám định',
  'INSPECTED': 'Nội dung đã giám định',
  'OPERATION TEST RESULT': 'Kết quả chạy thử',
  'PACKING': 'Đóng gói',
  'INSPECTION RESULT OF PACKING': 'Kết quả giám định đóng gói',
  'PHOTOGRAPHS OF INSPECTION ACTIVITY': 'Ảnh hoạt động giám định',
  'DOCUMENTS EXAMINED DURING INSPECTION': 'Tài liệu đã kiểm tra khi giám định',
  'DETAIL OF PRODUCT': 'Chi tiết sản phẩm',
  'ATTACHMENT': 'Tài liệu đính kèm',
  'CONCLUSION OF INSPECTION': 'Kết luận giám định',
  'Applicant’s person(s) in charge': 'Người phụ trách phía bên đề nghị',
  'INSPECTOR': 'Giám định viên',
  'DECLARED / APPLIED FOR INSPECTION': 'Nội dung khai báo / Nội dung đề nghị giám định',
  'QUALITY': 'Chất lượng',
  'RADIATION METER USED FOR INSPECTION': 'Máy đo phóng xạ dùng khi giám định',
  'RADIATION LEVEL FOUND': 'Mức phóng xạ đo được',
  'EXPLOSIVE MATERIAL': 'Vật liệu nổ',
  'ATTACHMENTS': 'Tài liệu đính kèm',
  'II. Inspection Result': 'II. Kết quả giám định',

  // ── 공통 필드
  'Result': 'Kết quả',
  'Date': 'Ngày',
  'Client': 'Khách hàng',
  'Job File No': 'Job File No (số quản lý)',
  'Job File No.': 'Job File No (số quản lý)',
  'Company name': 'Tên công ty',
  'Name': 'Họ tên',
  'Signature': 'Chữ ký',
  'Title': 'Chức vụ',
  'Contact points (Tel., email, etc.)': 'Thông tin liên hệ (điện thoại, email, v.v.)',
  'Company name or CERINS branch office name': 'Tên công ty hoặc tên chi nhánh CERINS',
  'Yes': 'Có',
  'No': 'Không',
  'YES': 'Có',
  'NO': 'Không',
  'Others': 'Khác',
  'Other': 'Khác',
  'Quantity': 'Số lượng',
  'Manufacturer': 'Nhà sản xuất',
  'Model': 'Model',
  'Serial No.': 'Số sê-ri',
  'Satisfactory': 'Đạt',
  'Unsatisfactory': 'Không đạt',
  'Conditional': 'Đạt có điều kiện',
  'Reject': 'Từ chối',
  'Abortive': 'Không thể giám định',
  'Re-inspection': 'Giám định lại',
  'Compliance': 'Phù hợp',
  'If unsatisfactory result or conditional, specify the reasons':
    'Nếu không đạt hoặc đạt có điều kiện, nêu lý do',
  'If unsatisfactory result, specify the reasons': 'Nếu không đạt, nêu lý do',
  'If not satisfactory, specify the reasons': 'Nếu không đạt, nêu lý do',

  // ── CEC
  'Declared goods description': 'Mô tả hàng hóa khai báo',
  'Product name (Representative)': 'Tên sản phẩm đại diện',
  'Total Quantity': 'Tổng số lượng',
  'Date of Inspection': 'Ngày giám định',
  'Operation Test': 'Chạy thử',
  'Packing': 'Đóng gói',
  'Loading Supervision': 'Giám sát xếp hàng',
  'Place of Inspection and Country (full address)':
    'Địa điểm giám định và quốc gia (địa chỉ đầy đủ)',
  'Round-Trip Travel Time (00:00 h)': 'Thời gian đi lại khứ hồi (00:00 h)',
  'Total Duration of Inspection Hours (00:00 h)': 'Tổng thời gian giám định (00:00 h)',
  'Time of Operation Test / Packing Inspection / Loading Supervision':
    'Thời gian chạy thử / giám định đóng gói / giám sát xếp hàng',
  'OT Date': 'Ngày chạy thử',
  'OT From': 'Chạy thử từ',
  'OT To': 'Chạy thử đến',
  'Pack Date': 'Ngày đóng gói',
  'Pack From': 'Đóng gói từ',
  'Pack To': 'Đóng gói đến',
  'Load Date': 'Ngày xếp hàng',
  'Load From': 'Xếp hàng từ',
  'Load To': 'Xếp hàng đến',
  'TYPE OF PACKING': 'Hình thức đóng gói',
  'Bulk': 'Hàng rời',
  'Break-bulk': 'Hàng bách hóa (break-bulk)',
  'Container': 'Container',
  'In case of break-bulk and/or container cargo':
    'Trường hợp hàng break-bulk và/hoặc hàng container',
  'Sl. No.': 'Số thứ tự',
  'Type of container (20’, 40’ …)': 'Loại container (20’, 40’ …)',
  'LCL / FCL': 'LCL / FCL',
  'Container No.': 'Số container',
  'Seal No.': 'Số seal (niêm phong)',
  'Quantity & type of break-bulk packing': 'Số lượng và loại đóng gói break-bulk',
  'Break-bulk: Type of packing': 'Break-bulk: loại đóng gói',
  'Break-bulk: Quantity of packing': 'Break-bulk: số lượng đóng gói',
  'Break-bulk: Remark if any': 'Break-bulk: ghi chú',
  'Other packing: Remark if any': 'Đóng gói khác: ghi chú',
  'Photograph(s) of the place of inspection with inspector':
    'Ảnh địa điểm giám định cùng giám định viên (bắt buộc)',
  'Photograph(s) of operation test at the place of inspection':
    'Ảnh chạy thử tại địa điểm giám định',
  'Photographs of each goods/package showing their name-plates (at least 4)':
    'Ảnh từng sản phẩm/kiện hàng thấy rõ nhãn máy (ít nhất 4 ảnh)',
  'Photographs of packing process': 'Ảnh quá trình đóng gói',
  'Photographs of container stuffing and sealing process (at least 6)':
    'Ảnh quá trình đóng hàng vào container và niêm phong (ít nhất 6 ảnh)',
  'Documents examined': 'Tài liệu đã kiểm tra',
  'Inspection Checklist/Points provided by Coordinator':
    'Danh mục kiểm tra do điều phối viên cung cấp',
  'Original (Purchase) Price Copy': 'Bản sao giá mua gốc',
  'Packing List': 'Phiếu đóng gói',
  'Proforma Invoice': 'Hóa đơn chiếu lệ',
  'Others – specify and attach/enclose': 'Khác – nêu rõ nội dung và đính kèm',
  'Product details': 'Chi tiết sản phẩm',
  'Goods description': 'Tên hàng',
  'Re-conditioned/repaired (Y/N)': 'Tân trang/sửa chữa (Y/N)',
  'Month & Year of manufacture': 'Tháng/năm sản xuất',
  'Model No./Serial No.': 'Số model/số sê-ri',
  'Country of Origin': 'Nước xuất xứ',
  'Nameplate (Y/N)': 'Có nhãn máy (Y/N)',
  'Attachment (if any)': 'Có tài liệu đính kèm',
  'If YES, list down and attach/enclose': 'Nếu có, liệt kê danh sách và đính kèm',
  'Attachment': 'Tài liệu đính kèm',

  // ── SCRAP
  'Importer name': 'Tên nhà nhập khẩu',
  'Exporter name': 'Tên nhà xuất khẩu',
  'Product name': 'Tên hàng',
  'Net weight': 'Trọng lượng tịnh',
  'Grade type': 'Loại tiêu chuẩn phân cấp',
  'ISRI grade': 'Cấp ISRI',
  'Steel grade': 'Mác thép',
  'Date of inspection': 'Ngày giám định',
  'Time of Inspection – From': 'Thời gian giám định – từ',
  'Time of Inspection – To': 'Thời gian giám định – đến',
  'Round-trip Travel Time': 'Thời gian đi lại khứ hồi',
  'Total Duration of Inspection Hours': 'Tổng thời gian giám định',
  'Place of inspection (full address)': 'Địa điểm giám định (địa chỉ đầy đủ)',
  'Quantity inspected / presented for inspection':
    'Số lượng đã giám định / số lượng xuất trình giám định',
  'Country of origin': 'Nước xuất xứ',
  'Weight – Net weight': 'Trọng lượng – tịnh',
  'Weight – Gross weight': 'Trọng lượng – cả bì',
  'Quality condition/grade': 'Tình trạng/cấp chất lượng',
  'Scrap': 'Phế liệu',
  'Secondary': 'Hàng thứ phẩm',
  'Defective': 'Hàng lỗi',
  'If other conditions or others are applicable, please specify':
    'Nếu thuộc trường hợp khác, vui lòng nêu rõ',
  'Shredded or Un-shredded': 'Đã băm hay chưa băm',
  'Shredded': 'Đã băm',
  'Un-shredded': 'Chưa băm',
  'Mixed': 'Hỗn hợp',
  'If mixed, please specify': 'Nếu là hỗn hợp, vui lòng nêu rõ',
  'Last date of calibration': 'Ngày hiệu chuẩn gần nhất',
  'Next date of calibration': 'Ngày hiệu chuẩn kế tiếp',
  'Background radiation level (µSv/h)': 'Mức phóng xạ nền tại nơi giám định (µSv/h)',
  'Maximum radiation level on the scrap (µSv/h)': 'Mức phóng xạ tối đa trên phế liệu (µSv/h)',
  'Size of container (20’/40’…)': 'Kích cỡ container (20’/40’…)',
  'Quantity & type (KG)': 'Số lượng và loại (KG)',
  'Container Radiation Level (µSv/h)': 'Mức phóng xạ của container (µSv/h)',
  'Pictures taken during inspection (date & time shown)':
    'Ảnh chụp trong quá trình giám định (hiển thị ngày giờ)',
  'Photograph(s) or video clipping of the place of inspection with PSIA inspector':
    'Ảnh/video địa điểm giám định cùng giám định viên PSIA',
  'Photograph(s) or video clipping of the testing instrument(s)': 'Ảnh/video thiết bị kiểm tra',
  'Photograph(s) or video clipping of the process of stuffing of containers':
    'Ảnh/video quá trình đóng hàng vào container',
  'Photograph(s) or video clipping of the sealing process': 'Ảnh/video quá trình niêm phong',
  'Video clips (at least 5 minutes)': 'Video (từ 5 phút trở lên)',
  'Weight tickets': 'Phiếu cân',
  'Documents examined during inspection': 'Tài liệu đã kiểm tra khi giám định',
  'Inspection checklist/point provided by Coordinator':
    'Danh mục kiểm tra do điều phối viên cung cấp',
  'Packing list': 'Phiếu đóng gói',
  'Proforma invoice': 'Hóa đơn chiếu lệ',
  'Weight ticket': 'Phiếu cân',
  'Supplementary documents for quality/quantity':
    'Tài liệu bổ sung chứng minh chất lượng/số lượng',
  'Other documents if any': 'Tài liệu khác',
  'Others if any – specify and attach': 'Khác – nêu rõ nội dung và đính kèm',

  // ── PSIC
  'ITEM NO': 'Số hạng mục',
  'REPORT NO.': 'Số báo cáo',
  'Description': 'Tên hàng',
  'BRAND': 'Nhãn hiệu',
  'Subcontractor': 'Nhà thầu phụ',
  'Factory No': 'Số nhà máy',
  'INSPECTION DATE': 'Ngày giám định',
  'PI# & PO No.': 'Số PI / PO',
  'Lot Size': 'Cỡ lô',
  'BAR CODE NO.': 'Số mã vạch',
  'INSPECTION RESULT': 'Kết quả giám định',
  'PASSED': 'Đạt',
  'FAILED': 'Không đạt',
  'PENDING': 'Tạm hoãn',
  'Remarks': 'Ghi chú',
  'Inspector': 'Giám định viên',
  'Subcontractor By': 'Người phụ trách nhà thầu phụ',
  'Reviewed': 'Người xem xét',
};
