/**
 * 폼 화면용 중국어(간체) 번역 사전 (영문 원문 → 중국어).
 * 화면 표시에만 쓰이고, 생성되는 Word 파일은 원본 영문 양식 그대로 유지된다.
 * 사전에 없는 문자열은 영문 원문이 그대로 노출된다.
 */
export const ZH: Record<string, string> = {
  // ── 화면 공통
  'Inspection Report Builder': '检验报告生成器',
  'Fill in the form, attach photos, and download the Word report.':
    '填写表单并附上照片后，即可下载 Word 检验报告。',
  'Upload': '直接上传',
  'Base Word file': '基础 Word 文件',
  'Photos': '照片附件',
  'Item': '货物',
  'Goods name': '货物名称',
  'delete': '删除',
  'Clear signature': '清除签名',
  'Tap to sign': '点击签名',
  'Re-sign': '重新签名',
  'Undo': '撤销一笔',
  'Erase all': '全部清除',
  'Cancel': '取消',
  'Use this signature': '使用此签名',
  'Reset form': '重置表单',
  'Download did not start? Tap here': '没有开始下载？请点击这里',
  'Entries are kept on this device, so you can close the browser and come back. Photos are not kept.':
    '输入内容保存在本设备，关闭浏览器后仍可继续填写。照片不会保存。',
  'Sign here with your mouse or finger.': '请用鼠标或手指签名。',
  'Videos are delivered in a zip with the Word file, not inside it.':
    '视频不会嵌入 Word 文件，而是与 Word 文件一起打包为 zip 下载。',
  '+ add {x}': '+ 添加{x}',
  'jpg / jpeg / png / webp, multiple allowed': 'jpg / jpeg / png / webp，可多选',
  'Done – download Word file': '完成 – 下载 Word 文件',
  'Generating…': '生成中…',
  'Selected': '已选择',
  ' file(s) selected': ' 个文件已选择',
  '+ add row': '+ 添加行',
  'Report name': '填写人姓名',
  'e.g. 유지환': '例）유지환',
  'Saved as: 260828_Inspection Report_name': '保存文件名格式：260828_CEC Inspection Report_姓名',
  'Admin page': '管理员页面',
  'The generated report is stored on the server; admins can download it again from the admin page.':
    '生成的报告会保存在服务器上，管理员可在管理员页面重新下载。',

  // ── 보고서 제목
  'CEC Inspection Report': 'CEC 检验报告',
  'PSIC Inspection Report (Scrap)': 'PSIC 检验报告（废料）',
  'Pre-Shipment Inspection Report': '装运前检验报告',

  // ── 섹션 제목
  'General Information': '基本信息',
  'GOODS DESCRIPTION / DECLARED / APPLIED FOR INSPECTION': '申报货物明细 / 检验申请内容',
  'INSPECTED': '检验内容',
  'OPERATION TEST RESULT': '运行测试结果',
  'PACKING': '包装',
  'INSPECTION RESULT OF PACKING': '包装检验结果',
  'PHOTOGRAPHS OF INSPECTION ACTIVITY': '检验作业照片',
  'DOCUMENTS EXAMINED DURING INSPECTION': '检验时查验的文件',
  'DETAIL OF PRODUCT': '产品明细',
  'ATTACHMENT': '附件',
  'CONCLUSION OF INSPECTION': '检验结论',
  'Applicant’s person(s) in charge': '申请方在场负责人',
  'INSPECTOR': '检验员',
  'DECLARED / APPLIED FOR INSPECTION': '申报内容 / 检验申请内容',
  'QUALITY': '质量',
  'RADIATION METER USED FOR INSPECTION': '检验所用辐射测量仪',
  'RADIATION LEVEL FOUND': '实测辐射水平',
  'EXPLOSIVE MATERIAL': '爆炸物',
  'ATTACHMENTS': '附件资料',
  'II. Inspection Result': 'II. 检验结果',

  // ── 공통 필드
  'Result': '结果',
  'Date': '日期',
  'Client': '客户',
  'Job File No': 'Job File No（管理编号）',
  'Job File No.': 'Job File No（管理编号）',
  'Company name': '公司名称',
  'Name': '姓名',
  'Signature': '签名',
  'Title': '职务',
  'Contact points (Tel., email, etc.)': '联系方式（电话、邮箱等）',
  'Company name or CERINS branch office name': '公司名称或 CERINS 分公司名称',
  'Yes': '是',
  'No': '否',
  'YES': '是',
  'NO': '否',
  'Others': '其他',
  'Other': '其他',
  'Quantity': '数量',
  'Manufacturer': '制造商',
  'Model': '型号',
  'Serial No.': '序列号',
  'Satisfactory': '合格',
  'Unsatisfactory': '不合格',
  'Conditional': '有条件合格',
  'Reject': '拒收',
  'Abortive': '无法检验',
  'Re-inspection': '复检',
  'Compliance': '符合',
  'If unsatisfactory result or conditional, specify the reasons': '不合格或有条件合格时的原因',
  'If unsatisfactory result, specify the reasons': '不合格时的原因',
  'If not satisfactory, specify the reasons': '非合格时的原因',

  // ── CEC
  'Declared goods description': '申报货物明细',
  'Product name (Representative)': '代表品名',
  'Total Quantity': '总数量',
  'Date of Inspection': '检验日期',
  'Operation Test': '运行测试',
  'Packing': '包装',
  'Loading Supervision': '装货监督',
  'Place of Inspection and Country (full address)': '检验地点及国家（完整地址）',
  'Round-Trip Travel Time (00:00 h)': '往返路程时间（00:00 h）',
  'Total Duration of Inspection Hours (00:00 h)': '检验总耗时（00:00 h）',
  'Time of Operation Test / Packing Inspection / Loading Supervision':
    '运行测试 / 包装检验 / 装货监督时间',
  'OT Date': '运行测试日期',
  'OT From': '运行测试开始',
  'OT To': '运行测试结束',
  'Pack Date': '包装日期',
  'Pack From': '包装开始',
  'Pack To': '包装结束',
  'Load Date': '装货日期',
  'Load From': '装货开始',
  'Load To': '装货结束',
  'TYPE OF PACKING': '包装形式',
  'Bulk': '散装',
  'Break-bulk': '件杂货',
  'Container': '集装箱',
  'In case of break-bulk and/or container cargo': '件杂货及/或集装箱货物的情况',
  'Sl. No.': '序号',
  'Type of container (20’, 40’ …)': '集装箱种类（20’、40’ 等）',
  'LCL / FCL': 'LCL / FCL（拼箱 / 整箱）',
  'Container No.': '集装箱号',
  'Seal No.': '铅封号',
  'Quantity & type of break-bulk packing': '件杂货包装数量及种类',
  'Break-bulk: Type of packing': '件杂货：包装种类',
  'Break-bulk: Quantity of packing': '件杂货：包装数量',
  'Break-bulk: Remark if any': '件杂货：备注',
  'Other packing: Remark if any': '其他包装：备注',
  'Photograph(s) of the place of inspection with inspector': '检验地点及检验员照片（必需）',
  'Photograph(s) of operation test at the place of inspection': '检验现场运行测试照片',
  'Photographs of each goods/package showing their name-plates (at least 4)':
    '可见铭牌的各产品/包装照片（至少 4 张）',
  'Photographs of packing process': '包装过程照片',
  'Photographs of container stuffing and sealing process (at least 6)':
    '集装箱装箱及施封过程照片（至少 6 张）',
  'Documents examined': '查验文件',
  'Inspection Checklist/Points provided by Coordinator': '协调员提供的检验清单',
  'Original (Purchase) Price Copy': '原采购价格副本',
  'Packing List': '装箱单',
  'Proforma Invoice': '形式发票',
  'Others – specify and attach/enclose': '其他 – 请注明内容并附上',
  'Product details': '产品明细',
  'Goods description': '品名',
  'Re-conditioned/repaired (Y/N)': '是否翻新/维修（Y/N）',
  'Month & Year of manufacture': '生产年月',
  'Model No./Serial No.': '型号/序列号',
  'Country of Origin': '原产地',
  'Nameplate (Y/N)': '有无铭牌（Y/N）',
  'Attachment (if any)': '有无附件',
  'If YES, list down and attach/enclose': '如为“是”，请列出清单并附上',
  'Attachment': '附件',

  // ── SCRAP
  'Importer name': '进口商名称',
  'Exporter name': '出口商名称',
  'Product name': '品名',
  'Net weight': '净重',
  'Grade type': '等级种类',
  'ISRI grade': 'ISRI 等级',
  'Steel grade': '钢种',
  'Date of inspection': '检验日期',
  'Time of Inspection – From': '检验时间 – 开始',
  'Time of Inspection – To': '检验时间 – 结束',
  'Round-trip Travel Time': '往返路程时间',
  'Total Duration of Inspection Hours': '检验总耗时',
  'Place of inspection (full address)': '检验地点（完整地址）',
  'Quantity inspected / presented for inspection': '受检数量 / 送检数量',
  'Country of origin': '原产地',
  'Weight – Net weight': '重量 – 净重',
  'Weight – Gross weight': '重量 – 毛重',
  'Quality condition/grade': '质量状态/等级',
  'Scrap': '废料',
  'Secondary': '次级品',
  'Defective': '不良品',
  'If other conditions or others are applicable, please specify': '属于其他情形时请注明内容',
  'Shredded or Un-shredded': '是否破碎',
  'Shredded': '已破碎',
  'Un-shredded': '未破碎',
  'Mixed': '混合',
  'If mixed, please specify': '混合时请注明内容',
  'Last date of calibration': '上次校准日期',
  'Next date of calibration': '下次校准日期',
  'Background radiation level (µSv/h)': '检验地点本底辐射水平（µSv/h）',
  'Maximum radiation level on the scrap (µSv/h)': '废料最大辐射水平（µSv/h）',
  'Size of container (20’/40’…)': '集装箱规格（20’/40’ 等）',
  'Quantity & type (KG)': '数量及种类（KG）',
  'Container Radiation Level (µSv/h)': '集装箱辐射水平（µSv/h）',
  'Pictures taken during inspection (date & time shown)': '检验过程照片（显示日期与时间）',
  'Photograph(s) or video clipping of the place of inspection with PSIA inspector':
    '检验地点及 PSIA 检验员的照片/视频',
  'Photograph(s) or video clipping of the testing instrument(s)': '检测仪器的照片/视频',
  'Photograph(s) or video clipping of the process of stuffing of containers': '集装箱装箱过程的照片/视频',
  'Photograph(s) or video clipping of the sealing process': '施封过程的照片/视频',
  'Video clips (at least 5 minutes)': '视频（5 分钟以上）',
  'Weight tickets': '磅单',
  'Documents examined during inspection': '检验时查验的文件',
  'Inspection checklist/point provided by Coordinator': '协调员提供的检验清单',
  'Packing list': '装箱单',
  'Proforma invoice': '形式发票',
  'Weight ticket': '磅单',
  'Supplementary documents for quality/quantity': '质量·数量的补充证明文件',
  'Other documents if any': '其他文件',
  'Others if any – specify and attach': '其他 – 请注明内容并附上',

  // ── PSIC
  'ITEM NO': '项目编号',
  'REPORT NO.': '报告编号',
  'Description': '品名',
  'BRAND': '品牌',
  'Subcontractor': '协作厂商',
  'Factory No': '工厂编号',
  'INSPECTION DATE': '检验日期',
  'PI# & PO No.': 'PI / PO 编号',
  'Lot Size': '批量数量',
  'BAR CODE NO.': '条形码编号',
  'INSPECTION RESULT': '检验结果',
  'PASSED': '合格',
  'FAILED': '不合格',
  'PENDING': '待定',
  'Remarks': '备注',
  'Inspector': '检验员',
  'Subcontractor By': '协作厂商负责人',
  'Reviewed': '审核人',
};
